spring.application.name=Hospital Patient Enquiries Standalone Worker
camunda.client.mode=self-managed
camunda.client.grpc-address=http://127.0.0.1:26500
camunda.client.rest-address=http://127.0.0.1:8080
camunda.client.prefer-rest-over-grpc=true
camunda.client.auth.method=none
hospital.enquiry.ledger-directory=./data/enquiry-demo-ledger
logging.level.io.camunda.client.impl.CamundaCallCredentials=ERROR
